---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonflask-1
  namespace: belajar
  labels:
    app: python-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      name: pythonflask-1
      labels:
        app: python-flask
    spec:
      containers:
        - name: pythonflask-1
          image: rizkypanz/helloflask:stable
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonflask-1-server
  namespace: belajar
spec:
  type: LoadBalancer
  selector:
    app: python-flask
  ports:
    - port: 5000
      targetPort: 5000
